# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import protobuf_pb2 as src_dot_protos_dot_protobuf__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareMessage = channel.unary_unary(
                '/Service/PrepareMessage',
                request_serializer=src_dot_protos_dot_protobuf__pb2.Message.SerializeToString,
                response_deserializer=src_dot_protos_dot_protobuf__pb2.IsValid.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/Service/SendMessage',
                request_serializer=src_dot_protos_dot_protobuf__pb2.Message.SerializeToString,
                response_deserializer=src_dot_protos_dot_protobuf__pb2.Empty.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareMessage,
                    request_deserializer=src_dot_protos_dot_protobuf__pb2.Message.FromString,
                    response_serializer=src_dot_protos_dot_protobuf__pb2.IsValid.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=src_dot_protos_dot_protobuf__pb2.Message.FromString,
                    response_serializer=src_dot_protos_dot_protobuf__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/PrepareMessage',
            src_dot_protos_dot_protobuf__pb2.Message.SerializeToString,
            src_dot_protos_dot_protobuf__pb2.IsValid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/SendMessage',
            src_dot_protos_dot_protobuf__pb2.Message.SerializeToString,
            src_dot_protos_dot_protobuf__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
